# Generated by Django 2.2.24 on 2021-08-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
